# Generated by Django 5.0.4 on 2024-04-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
